name: spacha_maker
description: A new Flutter project.

publish_to: 'none'

version: 1.0.1+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  app_tracking_transparency: ^2.0.2+1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  flutter_image_compress: ^1.1.3
  flutter_keyboard_visibility: ^5.4.0
  flutter_launcher_icons: ^0.11.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.16
  flutter_native_text_input: ^2.4.0
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  hooks_riverpod: ^2.1.3
  image: ^3.0.1
  image_cropper: ^3.0.1
  image_gallery_saver: ^1.7.1
  image_picker: ^0.8.6
  in_app_review: ^2.0.6
  intl: ^0.17.0
  introduction_screen: ^3.1.2
  json_annotation: ^4.7.0
  json_serializable: ^6.5.4
  keyboard_actions: ^4.1.0
  lottie: ^2.1.0
  page_transition: ^2.0.9
  path: ^1.8.2
  path_provider: ^2.0.11
  pdf: ^3.8.4
  pedantic_mono: ^1.20.1
  permission_handler: ^10.2.0
  printing: ^5.9.3
  riverpod: ^2.1.3
  share_plus: ^6.3.0
  shared_preferences: ^2.0.15
  sizer: ^2.0.15
  url_launcher: ^6.1.7

dev_dependencies:
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.1.0+1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: assets/images/app_icon.jpg
  ios: true
  android: true

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - assets/movies/
    - assets/lotties/